import {Profile} from "@/shared/lib/types/profile";

export const mockProfiles: Profile[] = [
    {
        id: '1',
        name: 'Sarah',
        age: 28,
        bio: 'Coffee enthusiast ☕ | Travel addict 🌍 | Dog mom 🐕',
        photos: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800'],
        distance: 3,
        interests: ['Travel', 'Photography', 'Coffee'],
        occupation: 'Marketing Manager',
    },
    {
        id: '2',
        name: 'Emily',
        age: 25,
        bio: 'Yoga instructor 🧘‍♀️ | Plant-based 🌱 | Beach lover 🏖️',
        photos: ['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800'],
        distance: 5,
        interests: ['Yoga', 'Fitness', 'Nature'],
        occupation: 'Yoga Instructor',
    },
    {
        id: '3',
        name: 'Jessica',
        age: 30,
        bio: 'Software Engineer 💻 | Gamer 🎮 | Cat person 🐱',
        photos: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800'],
        distance: 2,
        interests: ['Gaming', 'Tech', 'Anime'],
        occupation: 'Software Engineer',
    },
    {
        id: '4',
        name: 'Amanda',
        age: 27,
        bio: 'Foodie 🍜 | Wine connoisseur 🍷 | Weekend hiker ⛰️',
        photos: ['https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800'],
        distance: 7,
        interests: ['Food', 'Wine', 'Hiking'],
        occupation: 'Chef',
    },
    {
        id: '5',
        name: 'Olivia',
        age: 26,
        bio: 'Artist 🎨 | Music festival junkie 🎵 | Free spirit ✨',
        photos: ['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800'],
        distance: 4,
        interests: ['Art', 'Music', 'Festivals'],
        occupation: 'Graphic Designer',
    },
    {
        id: '6',
        name: 'Sophia',
        age: 29,
        bio: 'Medical student 👩‍⚕️ | Runner 🏃‍♀️ | Book worm 📚',
        photos: ['https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800'],
        distance: 6,
        interests: ['Reading', 'Running', 'Medicine'],
        occupation: 'Medical Student',
    },
    {
        id: '7',
        name: 'Mia',
        age: 24,
        bio: 'Fashion blogger 👗 | Vegan 🌿 | Sunset chaser 🌅',
        photos: ['https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?w=800'],
        distance: 8,
        interests: ['Fashion', 'Photography', 'Lifestyle'],
        occupation: 'Content Creator',
    },
    {
        id: '8',
        name: 'Ava',
        age: 31,
        bio: 'Entrepreneur 💼 | Fitness junkie 💪 | Adventure seeker 🏔️',
        photos: ['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800'],
        distance: 5,
        interests: ['Business', 'Fitness', 'Travel'],
        occupation: 'CEO',
    },
    {
        id: '9',
        name: 'Isabella',
        age: 27,
        bio: 'Dancer 💃 | Sushi lover 🍣 | Spontaneous traveler ✈️',
        photos: ['https://images.unsplash.com/photo-1502767089025-6572583495f9?w=800'],
        distance: 3,
        interests: ['Dance', 'Food', 'Travel'],
        occupation: 'Professional Dancer',
    },
    {
        id: '10',
        name: 'Charlotte',
        age: 26,
        bio: 'Photographer 📸 | Nature lover 🌲 | Golden hour enthusiast 🌄',
        photos: ['https://images.unsplash.com/photo-1496440737103-cd596325d314?w=800'],
        distance: 4,
        interests: ['Photography', 'Nature', 'Art'],
        occupation: 'Photographer',
    },
    {
        id: '11',
        name: 'Amelia',
        age: 28,
        bio: 'Teacher 📚 | Pottery maker 🏺 | Tea enthusiast 🍵',
        photos: ['https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?w=800'],
        distance: 6,
        interests: ['Education', 'Art', 'Crafts'],
        occupation: 'High School Teacher',
    },
    {
        id: '12',
        name: 'Evelyn',
        age: 25,
        bio: 'Marine biologist 🐠 | Scuba diver 🤿 | Ocean advocate 🌊',
        photos: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800'],
        distance: 10,
        interests: ['Marine Life', 'Diving', 'Environment'],
        occupation: 'Marine Biologist',
    },
    {
        id: '13',
        name: 'Abigail',
        age: 29,
        bio: 'Interior designer 🏠 | Plant parent 🪴 | Minimalist lifestyle ✨',
        photos: ['https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800'],
        distance: 5,
        interests: ['Design', 'Plants', 'Architecture'],
        occupation: 'Interior Designer',
    },
    {
        id: '14',
        name: 'Harper',
        age: 27,
        bio: 'Pilot ✈️ | Adrenaline junkie 🪂 | World explorer 🗺️',
        photos: ['https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=800'],
        distance: 12,
        interests: ['Aviation', 'Travel', 'Adventure'],
        occupation: 'Commercial Pilot',
    },
    {
        id: '15',
        name: 'Ella',
        age: 26,
        bio: 'Barista ☕ | Latte art master 🎨 | Early bird 🌅',
        photos: ['https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?w=800'],
        distance: 2,
        interests: ['Coffee', 'Art', 'People'],
        occupation: 'Coffee Shop Owner',
    },
    {
        id: '16',
        name: 'Scarlett',
        age: 30,
        bio: 'Lawyer ⚖️ | True crime podcast addict 🎧 | Wine nights 🍷',
        photos: ['https://images.unsplash.com/photo-1515077678510-ce3bdf418862?w=800'],
        distance: 7,
        interests: ['Law', 'Podcasts', 'Socializing'],
        occupation: 'Corporate Lawyer',
    },
    {
        id: '17',
        name: 'Grace',
        age: 24,
        bio: 'Musician 🎸 | Festival goer 🎪 | Night owl 🌙',
        photos: ['https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=800'],
        distance: 4,
        interests: ['Music', 'Concerts', 'Art'],
        occupation: 'Musician',
    },
    {
        id: '18',
        name: 'Chloe',
        age: 28,
        bio: 'Veterinarian 🐾 | Animal rescuer 🐕 | Hiking enthusiast ⛰️',
        photos: ['https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=800'],
        distance: 9,
        interests: ['Animals', 'Nature', 'Hiking'],
        occupation: 'Veterinarian',
    },
    {
        id: '19',
        name: 'Lily',
        age: 27,
        bio: 'Journalist ✍️ | Bookshop regular 📖 | Coffee addict ☕',
        photos: ['https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800'],
        distance: 3,
        interests: ['Writing', 'Reading', 'Journalism'],
        occupation: 'Journalist',
    },
    {
        id: '20',
        name: 'Zoe',
        age: 25,
        bio: 'Personal trainer 💪 | Meal prep queen 🥗 | Motivator 🔥',
        photos: ['https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=800'],
        distance: 5,
        interests: ['Fitness', 'Nutrition', 'Health'],
        occupation: 'Personal Trainer',
    },
];